#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit

./node_modules/.bin/jspm config endpoints.github.auth `echo -n $JSPM_GITHUB_AUTH_USERNAME:$JSPM_GITHUB_AUTH_TOKEN | base64`

grunt --stack --no-color "$@"
